language: php
php:
    - '7.3'

script:
    - composer test
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

install:
    - composer install

after_success:
    - bash <(curl -s https://codecov.io/bash)
