parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\Controller\:
        resource: '../src/Application/Controller/'
        tags: ['controller.service_arguments']

